import type { PluginManifest } from '@herta/shared';

export const lfgManifest: PluginManifest = {
  id: 'lfg',
  name: 'LFG',
  version: '1.0.0',
  description: 'Guild内のゲーム・イベント募集、参加、辞退、締切、履歴管理を提供します',
  author: { name: 'Herta' },
  category: 'game',
  permissions: [
    {
      id: 'lfg.manage',
      name: 'LFG 管理',
      description: '募集の閲覧、強制close/cancel、Plugin設定の管理',
    },
  ],
  dependencies: [],
  configSchema: {
    type: 'object',
    additionalProperties: false,
    properties: {
      maxOpenPostsPerGuild: {
        type: 'integer',
        title: 'Guild内の最大募集中件数',
        minimum: 1,
        maximum: 500,
        default: 50,
      },
      maxOpenPostsPerChannel: {
        type: 'integer',
        title: 'チャンネル内の最大募集中件数',
        minimum: 1,
        maximum: 100,
        default: 10,
      },
      creationCooldownSeconds: {
        type: 'integer',
        title: '募集作成Cooldown（秒）',
        minimum: 0,
        maximum: 3600,
        default: 30,
      },
      maxPlayersLimit: {
        type: 'integer',
        title: '募集可能な最大人数',
        minimum: 2,
        maximum: 500,
        default: 100,
      },
      defaultMaxPlayers: {
        type: 'integer',
        title: '新規募集の既定定員',
        description:
          'Studioで新しい募集を作る際の初期人数です。最大人数設定を超える場合は自動調整されます。',
        minimum: 2,
        maximum: 500,
        default: 4,
      },
      gamePresets: {
        type: 'array',
        title: 'ゲーム・イベントPreset',
        description:
          'Studioの募集作成フォームに候補として表示します。候補外の名前も自由入力できます。',
        maxItems: 30,
        items: { type: 'string', minLength: 1, maxLength: 80 },
        default: [
          'Minecraft',
          'VALORANT',
          'Apex Legends',
          'Fortnite',
          'Overwatch 2',
          'League of Legends',
          'Splatoon 3',
          'Monster Hunter Wilds',
          '雑談・イベント',
        ],
      },
      maxTitleLength: {
        type: 'integer',
        title: 'タイトル最大文字数',
        minimum: 1,
        maximum: 200,
        default: 100,
      },
      maxDescriptionLength: {
        type: 'integer',
        title: '説明最大文字数',
        minimum: 0,
        maximum: 2000,
        default: 1000,
      },
      defaultDurationMinutes: {
        type: 'integer',
        title: '既定募集期間（分）',
        minimum: 5,
        maximum: 10080,
        default: 180,
      },
      maxDurationMinutes: {
        type: 'integer',
        title: '最大募集期間（分）',
        minimum: 5,
        maximum: 43200,
        default: 10080,
      },
      allowUserMentions: {
        type: 'boolean',
        title: '説明内のユーザーメンションを許可する',
        description: '@everyone、@here、ロールメンションは常に拒否します',
        default: false,
      },
      retentionDays: {
        type: 'integer',
        title: '終了済み募集の保持日数',
        minimum: 1,
        maximum: 3650,
        default: 90,
      },
    },
    required: [
      'maxOpenPostsPerGuild',
      'maxOpenPostsPerChannel',
      'creationCooldownSeconds',
      'maxPlayersLimit',
      'defaultMaxPlayers',
      'gamePresets',
      'maxTitleLength',
      'maxDescriptionLength',
      'defaultDurationMinutes',
      'maxDurationMinutes',
      'allowUserMentions',
      'retentionDays',
    ],
  },
  events: ['interactionCreate', 'messageDelete'],
  commands: [
    {
      name: 'lfg',
      description: 'ゲーム・イベント募集を管理します',
      subcommands: [
        {
          name: 'create',
          description: '新しい募集を作成します',
          options: [
            { name: 'game', description: 'ゲームまたはイベント名', type: 'string', required: true },
            { name: 'title', description: '募集タイトル', type: 'string', required: true },
            {
              name: 'max_players',
              description: '作成者を含む定員',
              type: 'integer',
              required: true,
            },
            { name: 'description', description: '募集内容', type: 'string' },
            { name: 'start_time', description: '開始日時（ISO-8601）', type: 'string' },
            { name: 'duration_minutes', description: '募集期間（分）', type: 'integer' },
          ],
        },
        {
          name: 'show',
          description: '募集の詳細を表示します',
          options: [{ name: 'id', description: '募集ID', type: 'string', required: true }],
        },
        {
          name: 'list',
          description: '募集中のLFGを一覧表示します',
          options: [
            {
              name: 'status',
              description: 'statusで絞り込みます',
              type: 'string',
              choices: [
                { name: '募集中', value: 'open' },
                { name: '満員', value: 'full' },
                { name: '締切', value: 'closed' },
                { name: 'キャンセル', value: 'cancelled' },
                { name: '期限切れ', value: 'expired' },
              ],
            },
          ],
        },
        {
          name: 'close',
          description: '募集を締め切ります',
          options: [{ name: 'id', description: '募集ID', type: 'string', required: true }],
        },
        {
          name: 'cancel',
          description: '募集をキャンセルします',
          options: [{ name: 'id', description: '募集ID', type: 'string', required: true }],
        },
      ],
    },
  ],
};
