import type { PluginManifest } from '@herta/shared';

export const activityRulesManifest: PluginManifest = {
  id: 'activity-rules',
  name: 'Activity Rules',
  version: '1.1.0',
  description:
    'Community Activityの発言・リアクション・VC集計へ除外ルールとanti-spam設定を適用します',
  author: { name: 'Herta' },
  category: 'utility',
  permissions: [
    {
      id: 'activity-rules.manage',
      name: 'Activity Rules 管理',
      description: 'コミュニティ活動の集計対象・除外条件を管理します',
    },
  ],
  dependencies: [],
  configSchema: {
    type: 'object',
    additionalProperties: false,
    properties: {
      excludedTextChannelIds: {
        type: 'array',
        title: '発言・リアクション集計から除外するチャンネル',
        uniqueItems: true,
        maxItems: 50,
        default: [],
        items: { type: 'string', pattern: '^\\d+$' },
        'x-herta-ui': {
          section: '発言・リアクション集計',
          widget: 'discord-channel',
          multiple: true,
          placeholder: '除外するテキストチャンネルを選択',
          help: 'Botコマンド用・ログ用・spam用チャンネルなどをランキング集計から除外できます。',
        },
      },
      excludedRoleIds: {
        type: 'array',
        title: '活動集計から除外するRole',
        uniqueItems: true,
        maxItems: 50,
        default: [],
        items: { type: 'string', pattern: '^\\d+$' },
        'x-herta-ui': {
          section: '共通除外',
          widget: 'discord-role',
          multiple: true,
          placeholder: '集計対象外にするRoleを選択',
          help: '運営Bot、テストユーザー、集計対象外メンバーなどへ利用できます。',
        },
      },
      messageCooldownSeconds: {
        type: 'integer',
        title: '発言カウントCooldown（秒）',
        minimum: 0,
        maximum: 300,
        default: 0,
        'x-herta-ui': {
          section: '発言anti-spam',
          help: '0は全発言をカウントします。例: 10なら同一ユーザーの発言は10秒に1回まで集計します。',
        },
      },
      minimumMessageLength: {
        type: 'integer',
        title: '集計する最小メッセージ文字数',
        minimum: 0,
        maximum: 200,
        default: 0,
        'x-herta-ui': {
          section: '発言anti-spam',
          help: '0は文字数判定なしです。1以上の判定には既存のMessage Content Intentが必要です。Intentが無効な場合、この条件だけを安全にスキップします。',
        },
      },
      excludeCommandMessages: {
        type: 'boolean',
        title: 'コマンド形式のメッセージを発言数に含めない',
        default: false,
        'x-herta-ui': {
          section: '発言anti-spam',
          help: 'ONにすると、指定prefixで始まる通常メッセージをMessagesランキングから除外します。Discord Slash Command自体はInteractionとして処理されるため元から発言数には含まれません。本文判定にはMessage Content Intentが必要です。',
        },
      },
      commandPrefixes: {
        type: 'array',
        title: 'コマンドとして扱うprefix',
        uniqueItems: true,
        minItems: 1,
        maxItems: 10,
        default: ['/', '!'],
        items: { type: 'string', minLength: 1, maxLength: 5, pattern: '^\\S+$' },
        'x-herta-ui': {
          section: '発言anti-spam',
          placeholder: '例: / または !',
          help: 'コマンド形式除外をONにしたとき、メッセージ先頭で判定するprefixです。最大10件・1〜5文字です。',
        },
      },
      countReactionsGiven: {
        type: 'boolean',
        title: '付けたリアクションを集計する',
        default: true,
        'x-herta-ui': { section: 'リアクション集計' },
      },
      countReactionsReceived: {
        type: 'boolean',
        title: 'もらったリアクションを集計する',
        default: true,
        'x-herta-ui': { section: 'リアクション集計' },
      },
      excludedVoiceChannelIds: {
        type: 'array',
        title: 'VC滞在時間から除外するチャンネル',
        uniqueItems: true,
        maxItems: 50,
        default: [],
        items: { type: 'string', pattern: '^\\d+$' },
        'x-herta-ui': {
          section: 'VC集計',
          widget: 'discord-channel',
          multiple: true,
          placeholder: '集計しないVCを選択',
          help: 'AFK用・待機用・運営用VCなどを滞在時間ランキングから除外できます。',
        },
      },
      countSelfMutedVoice: {
        type: 'boolean',
        title: '自己ミュート中もVC時間を集計する',
        default: true,
        'x-herta-ui': { section: 'VC集計' },
      },
      countServerMutedVoice: {
        type: 'boolean',
        title: 'サーバーミュート中もVC時間を集計する',
        default: true,
        'x-herta-ui': { section: 'VC集計' },
      },
      countSelfDeafenedVoice: {
        type: 'boolean',
        title: '自己スピーカーミュート中もVC時間を集計する',
        default: true,
        'x-herta-ui': { section: 'VC集計' },
      },
      countServerDeafenedVoice: {
        type: 'boolean',
        title: 'サーバースピーカーミュート中もVC時間を集計する',
        default: true,
        'x-herta-ui': { section: 'VC集計' },
      },
    },
    required: [
      'excludedTextChannelIds',
      'excludedRoleIds',
      'messageCooldownSeconds',
      'minimumMessageLength',
      'excludeCommandMessages',
      'commandPrefixes',
      'countReactionsGiven',
      'countReactionsReceived',
      'excludedVoiceChannelIds',
      'countSelfMutedVoice',
      'countServerMutedVoice',
      'countSelfDeafenedVoice',
      'countServerDeafenedVoice',
    ],
  },
  events: [],
  commands: [],
};
