import type { PluginManifest } from '@herta/shared';

const metricChoices = [
  { name: 'XP', value: 'xp' },
  { name: 'Level', value: 'level' },
  { name: '発言数', value: 'messages' },
  { name: 'Reaction', value: 'reactions' },
  { name: 'Voice', value: 'voice' },
  { name: 'Minecraft', value: 'minecraft' },
  { name: 'Achievements', value: 'achievements' },
  { name: 'Season Point', value: 'season' },
] as const;

const periodChoices = [
  { name: 'All Time', value: 'all' },
  { name: '直近7日', value: '7d' },
  { name: '直近30日', value: '30d' },
  { name: 'Current Season', value: 'season' },
] as const;

export const xpLevelManifest: PluginManifest = {
  id: 'xp-level',
  name: 'XP / Level',
  version: '1.2.0',
  description: 'XP・Level・Community活動ランキング・Level Roleを提供します',
  author: { name: 'Herta' },
  category: 'utility',
  permissions: [
    {
      id: 'xp-level.manage',
      name: 'XP / Level 管理',
      description: 'XP付与条件・通知・Level Role設定を管理します',
    },
  ],
  dependencies: [],
  configSchema: {
    type: 'object',
    additionalProperties: false,
    properties: {
      enabled: {
        type: 'boolean',
        title: 'XP / Levelを有効化する',
        default: true,
        'x-herta-ui': { section: '基本設定' },
      },
      xpPerMessage: {
        type: 'integer',
        title: '1メッセージあたりのXP',
        minimum: 1,
        maximum: 100,
        default: 10,
        'x-herta-ui': {
          section: 'XP設定',
          help: 'Cooldownを通過した通常メッセージ1件に付与するXPです。',
        },
      },
      cooldownSeconds: {
        type: 'integer',
        title: 'XP付与Cooldown（秒）',
        minimum: 5,
        maximum: 600,
        default: 60,
        'x-herta-ui': {
          section: 'XP設定',
          help: '短時間の連投でXPを稼ぎにくくします。',
        },
      },
      excludeCommandMessages: {
        type: 'boolean',
        title: 'コマンド形式のメッセージへXPを付与しない',
        default: false,
        'x-herta-ui': {
          section: 'XP設定',
          help: 'ONにすると、指定prefixで始まる通常メッセージをXP付与対象から外します。Discord Slash Commandは元からMessageCreateのXP対象ではありません。',
        },
      },
      commandPrefixes: {
        type: 'array',
        title: 'XP対象外にするコマンドprefix',
        uniqueItems: true,
        maxItems: 10,
        default: ['/', '!'],
        items: { type: 'string', minLength: 1, maxLength: 5, pattern: '^\\S+$' },
        'x-herta-ui': {
          section: 'XP設定',
          help: '例: /, !, ?, .。先頭の空白は無視して判定します。',
        },
      },
      excludedChannelIds: {
        type: 'array',
        title: 'XP付与から除外するチャンネル',
        uniqueItems: true,
        maxItems: 25,
        default: [],
        items: { type: 'string', pattern: '^\\d+$' },
        'x-herta-ui': {
          section: '除外設定',
          widget: 'discord-channel',
          multiple: true,
          placeholder: '除外するチャンネルを選択',
        },
      },
      excludedRoleIds: {
        type: 'array',
        title: 'XP付与から除外するRole',
        uniqueItems: true,
        maxItems: 25,
        default: [],
        items: { type: 'string', pattern: '^\\d+$' },
        'x-herta-ui': {
          section: '除外設定',
          widget: 'discord-role',
          multiple: true,
          placeholder: '除外するRoleを選択',
        },
      },
      levelUpNotification: {
        type: 'boolean',
        title: 'レベルアップを通知する',
        default: true,
        'x-herta-ui': { section: '通知' },
      },
      levelUpChannelId: {
        type: ['string', 'null'],
        title: 'レベルアップ通知チャンネル',
        default: null,
        'x-herta-ui': {
          section: '通知',
          widget: 'discord-channel',
          placeholder: '通知先を選択（未設定は発言チャンネル）',
          help: '未設定の場合はレベルアップしたメッセージのチャンネルへ通知します。',
        },
      },
      leaderboardSize: {
        type: 'integer',
        title: 'Leaderboard表示人数',
        minimum: 5,
        maximum: 25,
        default: 10,
        'x-herta-ui': { section: '表示設定' },
      },
      reward1Level: {
        type: 'integer',
        title: 'Level Role 1の到達レベル',
        minimum: 1,
        maximum: 999,
        default: 5,
        'x-herta-ui': { section: 'Level Role' },
      },
      reward1RoleId: {
        type: ['string', 'null'],
        title: 'Level Role 1',
        default: null,
        'x-herta-ui': {
          section: 'Level Role',
          widget: 'discord-role',
          editableOnly: true,
          placeholder: 'Lv.5などで付与するRoleを選択',
        },
      },
      reward2Level: {
        type: 'integer',
        title: 'Level Role 2の到達レベル',
        minimum: 1,
        maximum: 999,
        default: 10,
        'x-herta-ui': { section: 'Level Role' },
      },
      reward2RoleId: {
        type: ['string', 'null'],
        title: 'Level Role 2',
        default: null,
        'x-herta-ui': {
          section: 'Level Role',
          widget: 'discord-role',
          editableOnly: true,
          placeholder: 'Lv.10などで付与するRoleを選択',
        },
      },
      reward3Level: {
        type: 'integer',
        title: 'Level Role 3の到達レベル',
        minimum: 1,
        maximum: 999,
        default: 20,
        'x-herta-ui': { section: 'Level Role' },
      },
      reward3RoleId: {
        type: ['string', 'null'],
        title: 'Level Role 3',
        default: null,
        'x-herta-ui': {
          section: 'Level Role',
          widget: 'discord-role',
          editableOnly: true,
          placeholder: 'Lv.20などで付与するRoleを選択',
        },
      },
    },
    required: [
      'enabled',
      'xpPerMessage',
      'cooldownSeconds',
      'excludeCommandMessages',
      'commandPrefixes',
      'excludedChannelIds',
      'excludedRoleIds',
      'levelUpNotification',
      'levelUpChannelId',
      'leaderboardSize',
      'reward1Level',
      'reward1RoleId',
      'reward2Level',
      'reward2RoleId',
      'reward3Level',
      'reward3RoleId',
    ],
  },
  events: ['messageCreate'],
  commands: [
    {
      name: 'rank',
      description: '自分やメンバーのCommunity Rankを表示します',
      options: [
        {
          name: 'user',
          description: '確認するメンバー（未指定は自分）',
          type: 'user',
        },
        {
          name: 'metric',
          description: '確認するランキング指標（未指定はXP）',
          type: 'string',
          choices: [...metricChoices],
        },
        {
          name: 'period',
          description: '集計期間（指標に対応しない期間は自動補正）',
          type: 'string',
          choices: [...periodChoices],
        },
      ],
    },
    {
      name: 'leaderboard',
      description: 'サーバーのCommunityランキングを表示します',
      options: [
        {
          name: 'metric',
          description: 'ランキング指標（未指定はXP）',
          type: 'string',
          choices: [...metricChoices],
        },
        {
          name: 'period',
          description: '集計期間（指標に対応しない期間は自動補正）',
          type: 'string',
          choices: [...periodChoices],
        },
        {
          name: 'limit',
          description: '表示人数（未指定はPlugin設定）',
          type: 'integer',
          minValue: 5,
          maxValue: 25,
        },
      ],
    },
  ],
};
