import type { PluginManifest } from '@herta/shared';

export const xpLevelManifest: PluginManifest = {
  id: 'xp-level',
  name: 'XP / Level',
  version: '1.0.0',
  description: 'メッセージ活動に応じたXP・レベル・ランキング・Level Roleを提供します',
  author: { name: 'Herta' },
  category: 'utility',
  permissions: [
    {
      id: 'xp-level.manage',
      name: 'XP / Level 管理',
      description: 'XP付与条件・通知・Level Role設定を管理します',
    },
  ],
  dependencies: [],
  configSchema: {
    type: 'object',
    additionalProperties: false,
    properties: {
      enabled: {
        type: 'boolean',
        title: 'XP / Levelを有効化する',
        default: true,
        'x-herta-ui': { section: '基本設定' },
      },
      xpPerMessage: {
        type: 'integer',
        title: '1メッセージあたりのXP',
        minimum: 1,
        maximum: 100,
        default: 10,
        'x-herta-ui': {
          section: 'XP設定',
          help: 'Cooldownを通過した通常メッセージ1件に付与するXPです。',
        },
      },
      cooldownSeconds: {
        type: 'integer',
        title: 'XP付与Cooldown（秒）',
        minimum: 5,
        maximum: 600,
        default: 60,
        'x-herta-ui': {
          section: 'XP設定',
          help: '短時間の連投でXPを稼ぎにくくします。',
        },
      },
      excludedChannelIds: {
        type: 'array',
        title: 'XP付与から除外するチャンネル',
        uniqueItems: true,
        maxItems: 25,
        default: [],
        items: { type: 'string', pattern: '^\\d+$' },
        'x-herta-ui': {
          section: '除外設定',
          widget: 'discord-channel',
          multiple: true,
          placeholder: '除外するチャンネルを選択',
        },
      },
      excludedRoleIds: {
        type: 'array',
        title: 'XP付与から除外するRole',
        uniqueItems: true,
        maxItems: 25,
        default: [],
        items: { type: 'string', pattern: '^\\d+$' },
        'x-herta-ui': {
          section: '除外設定',
          widget: 'discord-role',
          multiple: true,
          placeholder: '除外するRoleを選択',
        },
      },
      levelUpNotification: {
        type: 'boolean',
        title: 'レベルアップを通知する',
        default: true,
        'x-herta-ui': { section: '通知' },
      },
      levelUpChannelId: {
        type: ['string', 'null'],
        title: 'レベルアップ通知チャンネル',
        default: null,
        'x-herta-ui': {
          section: '通知',
          widget: 'discord-channel',
          placeholder: '通知先を選択（未設定は発言チャンネル）',
          help: '未設定の場合はレベルアップしたメッセージのチャンネルへ通知します。',
        },
      },
      leaderboardSize: {
        type: 'integer',
        title: 'Leaderboard表示人数',
        minimum: 5,
        maximum: 25,
        default: 10,
        'x-herta-ui': { section: '表示設定' },
      },
      reward1Level: {
        type: 'integer',
        title: 'Level Role 1の到達レベル',
        minimum: 1,
        maximum: 999,
        default: 5,
        'x-herta-ui': { section: 'Level Role' },
      },
      reward1RoleId: {
        type: ['string', 'null'],
        title: 'Level Role 1',
        default: null,
        'x-herta-ui': {
          section: 'Level Role',
          widget: 'discord-role',
          editableOnly: true,
          placeholder: 'Lv.5などで付与するRoleを選択',
        },
      },
      reward2Level: {
        type: 'integer',
        title: 'Level Role 2の到達レベル',
        minimum: 1,
        maximum: 999,
        default: 10,
        'x-herta-ui': { section: 'Level Role' },
      },
      reward2RoleId: {
        type: ['string', 'null'],
        title: 'Level Role 2',
        default: null,
        'x-herta-ui': {
          section: 'Level Role',
          widget: 'discord-role',
          editableOnly: true,
          placeholder: 'Lv.10などで付与するRoleを選択',
        },
      },
      reward3Level: {
        type: 'integer',
        title: 'Level Role 3の到達レベル',
        minimum: 1,
        maximum: 999,
        default: 20,
        'x-herta-ui': { section: 'Level Role' },
      },
      reward3RoleId: {
        type: ['string', 'null'],
        title: 'Level Role 3',
        default: null,
        'x-herta-ui': {
          section: 'Level Role',
          widget: 'discord-role',
          editableOnly: true,
          placeholder: 'Lv.20などで付与するRoleを選択',
        },
      },
    },
    required: [
      'enabled',
      'xpPerMessage',
      'cooldownSeconds',
      'excludedChannelIds',
      'excludedRoleIds',
      'levelUpNotification',
      'levelUpChannelId',
      'leaderboardSize',
      'reward1Level',
      'reward1RoleId',
      'reward2Level',
      'reward2RoleId',
      'reward3Level',
      'reward3RoleId',
    ],
  },
  events: ['messageCreate'],
  commands: [
    {
      name: 'rank',
      description: '自分のXP・レベル・次レベルまでの進捗を表示します',
    },
    {
      name: 'leaderboard',
      description: 'サーバーのXPランキングを表示します',
    },
  ],
};
