import type { PluginManifest } from '@herta/shared';

export const autoResponseManifest: PluginManifest = {
  id: 'auto-response',
  name: 'Auto Response',
  version: '1.0.0',
  description: 'Guildごとの安全なキーワード・正規表現自動応答を管理します',
  author: { name: 'Herta' },
  category: 'utility',
  permissions: [
    {
      id: 'auto-response.manage',
      name: 'Auto Response 管理',
      description: '自動応答ルールの追加・編集・削除',
    },
  ],
  dependencies: [],
  configSchema: {
    type: 'object',
    additionalProperties: false,
    properties: {
      maxRules: {
        type: 'integer',
        title: 'ルール上限',
        minimum: 1,
        maximum: 200,
        default: 100,
      },
      maxRulesPerMessage: {
        type: 'integer',
        title: '1メッセージあたりの最大応答数',
        minimum: 1,
        maximum: 5,
        default: 1,
      },
      guildCooldownSeconds: {
        type: 'integer',
        title: 'Guild全体のCooldown秒数',
        minimum: 0,
        maximum: 3600,
        default: 1,
      },
      defaultRuleCooldownSeconds: {
        type: 'integer',
        title: '新規ルールの既定Cooldown秒数',
        minimum: 0,
        maximum: 86400,
        default: 5,
      },
      maxTriggerLength: {
        type: 'integer',
        title: 'トリガー最大文字数',
        minimum: 1,
        maximum: 200,
        default: 100,
      },
      maxResponseLength: {
        type: 'integer',
        title: '応答最大文字数',
        minimum: 1,
        maximum: 2000,
        default: 1800,
      },
      maxMessageLength: {
        type: 'integer',
        title: '評価対象メッセージ最大文字数',
        minimum: 1,
        maximum: 4000,
        default: 2000,
      },
      maxRegexEvaluationsPerMessage: {
        type: 'integer',
        title: '1メッセージあたりの正規表現評価上限',
        minimum: 1,
        maximum: 10,
        default: 5,
      },
      regexEnabled: {
        type: 'boolean',
        title: '正規表現ルールを許可',
        default: true,
      },
      regexMaxLength: {
        type: 'integer',
        title: '正規表現最大文字数',
        minimum: 1,
        maximum: 200,
        default: 100,
      },
      regexExecutionBudgetMs: {
        type: 'integer',
        title: '正規表現評価時間の警戒値（ms）',
        minimum: 1,
        maximum: 50,
        default: 10,
      },
      allowUserMentions: {
        type: 'boolean',
        title: 'ユーザーメンション通知を許可',
        description: '@everyone、@here、ロールメンションは常に拒否します',
        default: false,
      },
    },
    required: [
      'maxRules',
      'maxRulesPerMessage',
      'guildCooldownSeconds',
      'defaultRuleCooldownSeconds',
      'maxTriggerLength',
      'maxResponseLength',
      'maxMessageLength',
      'maxRegexEvaluationsPerMessage',
      'regexEnabled',
      'regexMaxLength',
      'regexExecutionBudgetMs',
      'allowUserMentions',
    ],
  },
  events: ['messageCreate'],
  commands: [],
};
